routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/**
 * ----------------------------------------------
 * Admin Routes
 * ----------------------------------------------
 * 
 * Here is where you can register your admin panel routes.
 */
Route::group(['middleware' => ['auth']], function () {
    Route::get('/', 'BackendController@dashboard')->name('admin');
    
    // Profiles
    Route::namespace('Profile')->prefix('profile')->group(function() {
        Route::get('/{id}', 'ProfileController@index')->name('profile.index');
        // Update profile
        Route::put('/{id}/update', 'ProfileController@update')->name('profile.update');
        // Remove Image
        Route::get('/{id}/image/deleted', 'ProfileController@deleteImage')->name('image.delete');
        // Delete Profile
        Route::delete('/{id}/profile/delete', 'ProfileController@delete')->name('profile.delete');
    
        // Change Password
        Route::put('/{id}/password/update', 'PasswordController@update')->name('password.change');
    });
    
    // Master Route
    Route::namespace('Master')->prefix('master')->group(function () {
        Route::get('/user/datatables', 'UserController@userDataTables');
        Route::resource('user', 'UserController');
        Route::get('/role/datatables', 'RoleController@roleDataTables');
        Route::resource('role', 'RoleController');
    });
    
    // General Route
    Route::get('/takmir/datatables', 'TakmirController@takmirDataTables');
    Route::resource('takmir', 'TakmirController');
    Route::get('/announcement/datatables', 'AnnouncementController@announcementsDataTables');
    Route::resource('announcement', 'AnnouncementController');
    Route::get('/kajian/datatables', 'KajianController@kajianDataTables');
    Route::resource('kajian', 'KajianController');
    Route::get('/gallery/datatables', 'GalleryController@galleryDataTables');
    Route::resource('gallery', 'GalleryController');
    Route::get('/contact/datatables', 'ContactController@contactDataTables');
    Route::resource('contact', 'ContactController');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@home')->name('home');
Route::get('/announcement', 'AnnouncementController@index')->name('announcement');
Route::get('/announcement/detail/{id}', 'AnnouncementController@show')->name('announc.detail');
Route::get('/donate', 'FrontController@donate')->name('donate');
Route::get('/kajian', 'KajianController@index')->name('kajian');
Route::get('/kajian/detail/{id}', 'KajianController@show')->name('kajian.detail');
Route::post('/contact', 'ContactController@store')->name('contact.send');

Auth::routes();

Route::get('/home', 'HomeController@index');

app/Models/Admin/Role.php
<?php

namespace App\Models\Admin;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use App\Models\Admin\Traits\RoleRelation;

class Role extends Model
{
    use RoleRelation;

    /**
     * Formatted Created At
     */
    public function getFormattedCreatedAt() {
        return Carbon::parse($this->created_at)->diffForHumans();
    }

    /**
     * Formatted Updated At
     */
    public function getFormattedUpdatedAt() {
        return Carbon::parse($this->updated)->diffForHumans();
    }
}

app/Http/Controllers/Admin/Master/RoleController.php
<?php

namespace App\Http\Controllers\Admin\Master;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Gate;
use App\Http\Requests\Admin\RoleRequest;
use App\Interfaces\Admin\Master\RoleInterface;

class RoleController extends Controller
{
    protected $roleInterface;

    public function __construct(RoleInterface $roleInterface) {
        $this->roleInterface = $roleInterface;

        // Only admin can access this resource
        $this->middleware(function($request, $next) {
            if(Gate::allows('is_admin')) return $next($request);
            abort(403, config('globalvar.admin_gate_message'));
        });
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.pages.master.roles.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $role = $this->roleInterface->newRole();

        return view('backend.pages.master.roles.create', compact('role'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RoleRequest $request)
    {
        return $this->roleInterface->storeToDB($request);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $role = $this->roleInterface->getRoleById($id);

        return view('backend.pages.master.roles.show', compact('role'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = $this->roleInterface->getRoleById($id);

        return view('backend.pages.master.roles.create', compact('role'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(RoleRequest $request, $id)
    {
        return $this->roleInterface->storeToDB($request, $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return $this->roleInterface->deleteRole($id);
    }

    /**
     * Get role datatables
     * 
     * @param Request
     */
    public function roleDataTables(Request $request)
    {
        return $this->roleInterface->requestRoles($request);
    }
}

app/Http/Controllers/Admin/Master/UserController.php
<?php

namespace App\Http\Controllers\Admin\Master;

use App\Models\Admin\Role;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Gate;
use App\Http\Requests\Admin\UserRequest;
use App\Interfaces\Admin\Master\UserInterface;

class UserController extends Controller
{
    protected $userInterface;
    protected $roleModel;

    public function __construct(UserInterface $userInterface, Role $role) {
        $this->userInterface = $userInterface;
        $this->roleModel = $role;

        // Only admin can access this resource
        $this->middleware(function($request, $next) {
            if(Gate::allows('is_admin')) return $next($request);
            abort(403, config('globalvar.admin_gate_message'));
        });
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.pages.master.users.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = $this->userInterface->newUser();
        $roles = $this->roleModel->all();

        return view('backend.pages.master.users.create', compact('user', 'roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        return $this->userInterface->storeToDB($request);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = $this->userInterface->getUserById($id);

        return view('backend.pages.master.users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = $this->userInterface->getUserById($id);
        $roles = $this->roleModel->all();

        return view('backend.pages.master.users.create', compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, $id)
    {
        return $this->userInterface->storeToDB($request, $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return $this->userInterface->deleteUser($id);
    }

    /**
     * Get user datatables
     * 
     * @param Request $request
     */
    public function userDataTables(Request $request) 
    {
        return $this->userInterface->requestUsers($request);
    }
}

resources/views/backend/pages/master/roles/create.blade.php
{!! Form::model($role, [
  'route' => $role->exists ? ['role.update', $role->id] : 'role.store',
  'method' => $role->exists ? 'PUT' : 'POST'
]) !!}

  <div class="form-group">
    {!! Form::label('name', 'Nama') !!}
    {!! Form::text('name', $role->exists ? $role->name : null, ['class' => 'form-control']) !!}
  </div>

{!! Form::close() !!}

resources/views/backend/pages/master/roles/index.blade.php
@extends('backend.layouts.app')

@section('section-header')
    {{ __('Hak Akses') }}
@endsection

@section('breadcrumbs')
    {{ Breadcrumbs::render('role') }}
@endsection

@section('section-body')
    {{-- Flash Messages --}}
    @include('backend.components.alerts')
    <div class="card">
        <div class="card-header">
            <a href="{{ route('role.create') }}" class="btn btn-sm btn-primary" id="btn-modal-show" title="{{ __('Tambah Hak Akses') }}">
                <i class="fas fa-plus"></i>
            </a>
            <a href="{{ route('role.index') }}" class="btn btn-sm btn-success ml-2" id="refresh-data" title="{{ __('Segarkan') }}">
                <i class="fas fa-sync" id="refresh-animation"></i>
            </a>
        </div>

        <div class="card-body">
            <div class="table table-responsive">
                <table class="table-striped" id="datatable" style="width: 100%">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>{{ __('Nama') }}</th>
                            <th>{{ __('Aksi') }}</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script src="{{ asset('backend/develop/js/dataTablesService.js') }}"></script>
    <script src="{{ asset('backend/develop/js/admin/roles/index.js') }}"></script>
@endpush

resources/views/backend/pages/master/roles/show.blade.php
<table class="table table-striped">
  <tr>
    <th>Name</th>
    <td>:</td>
    <td>
      {{ strtoupper($role->name) }}
    </td>
  </tr>

  <tr>
    <th>Created At</th>
    <td>:</td>
    <td>
      {{ $role->created_at }} 
      ({{ $role->getFormattedCreatedAt() }})
    </td>
  </tr>

  <tr>
    <th>Updated At</th>
    <td>:</td>
    <td>
      {{ $role->updated_at }} 
      ({{ $role->getFormattedUpdatedAt() }})
    </td>
  </tr>
</table>