routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/**
 * ----------------------------------------------
 * Admin Routes
 * ----------------------------------------------
 * 
 * Here is where you can register your admin panel routes.
 */
Route::group(['middleware' => ['auth']], function () {
    Route::get('/', 'BackendController@dashboard')->name('admin');
    
    // Profiles
    Route::namespace('Profile')->prefix('profile')->group(function() {
        Route::get('/{id}', 'ProfileController@index')->name('profile.index');
        // Update profile
        Route::put('/{id}/update', 'ProfileController@update')->name('profile.update');
        // Remove Image
        Route::get('/{id}/image/deleted', 'ProfileController@deleteImage')->name('image.delete');
        // Delete Profile
        Route::delete('/{id}/profile/delete', 'ProfileController@delete')->name('profile.delete');
    
        // Change Password
        Route::put('/{id}/password/update', 'PasswordController@update')->name('password.change');
    });
    
    // Master Route
    Route::namespace('Master')->prefix('master')->group(function () {
        Route::get('/user/datatables', 'UserController@userDataTables');
        Route::resource('user', 'UserController');
        Route::get('/role/datatables', 'RoleController@roleDataTables');
        Route::resource('role', 'RoleController');
    });
    
    // General Route
    Route::get('/takmir/datatables', 'TakmirController@takmirDataTables');
    Route::resource('takmir', 'TakmirController');
    Route::get('/announcement/datatables', 'AnnouncementController@announcementsDataTables');
    Route::resource('announcement', 'AnnouncementController');
    Route::get('/kajian/datatables', 'KajianController@kajianDataTables');
    Route::resource('kajian', 'KajianController');
    Route::get('/gallery/datatables', 'GalleryController@galleryDataTables');
    Route::resource('gallery', 'GalleryController');
    Route::get('/contact/datatables', 'ContactController@contactDataTables');
    Route::resource('contact', 'ContactController');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@home')->name('home');
Route::get('/announcement', 'AnnouncementController@index')->name('announcement');
Route::get('/announcement/detail/{id}', 'AnnouncementController@show')->name('announc.detail');
Route::get('/donate', 'FrontController@donate')->name('donate');
Route::get('/kajian', 'KajianController@index')->name('kajian');
Route::get('/kajian/detail/{id}', 'KajianController@show')->name('kajian.detail');
Route::post('/contact', 'ContactController@store')->name('contact.send');

Auth::routes();

Route::get('/home', 'HomeController@index');

app/Models/Admin/Announcement.php
<?php

namespace App\Models\Admin;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Announcement extends Model
{
    /**
     * Get formatted created_at
     */
    public function getFormattedCreatedAt() {
        return Carbon::parse($this->created_at)->diffForHumans();
    }
}

app/Http/Controllers/Admin/AnnouncementController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Gate;
use App\Http\Requests\Admin\AnnouncementRequest;
use App\Interfaces\Admin\General\AnnouncementInterface;

class AnnouncementController extends Controller
{
    protected $interface;

    public function __construct(AnnouncementInterface $interface) {
        $this->interface = $interface;

        // Only admin and petugas can access this resource
        $this->middleware(function ($request, $next) {
            if (Gate::allows('admin_and_petugas')) return $next($request);
            abort(403, config('globalvar.unauthorized'));
        });
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.pages.general.announcements.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $announcement = $this->interface->newAnnouncement();

        return view('backend.pages.general.announcements.create', compact('announcement'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AnnouncementRequest $request)
    {
        return $this->interface->storeToDB($request);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $announcement = $this->interface->getAnnouncementById($id);
        return view('backend.pages.general.announcements.show', compact('announcement'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $announcement = $this->interface->getAnnouncementById($id);
        return view('backend.pages.general.announcements.create', compact('announcement'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AnnouncementRequest $request, $id)
    {
        return $this->interface->storeToDB($request, $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return $this->interface->deleteAnnouncement($id);
    }

    /**
     * Get Announcements DataTables
     */
    public function announcementsDataTables(Request $request) {
        return $this->interface->requestAnnouncements($request);
    }
}

app/Http/Controllers/AnnouncementController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Admin\Announcement;

class AnnouncementController extends Controller
{
    public function index() {
        $announcements = Announcement::all();

        return view('frontend.pages.announcement.index', compact('announcements'));
    }

    public function show($id) {
        $announcement = Announcement::findOrFail($id);

        return view('frontend.pages.announcement.show', compact('announcement')); 
    }
}

resources/views/backend/pages/general/announcements/create.blade.php
@extends('backend.layouts.app')

@section('section-header')
    {{ $announcement->exists ? 'Ubah ' . $announcement->title : 'Buat Pengumuman Baru' }}
@endsection

@section('breadcrumbs')
    {{ Breadcrumbs::render('store-announcement', $announcement) }}
@endsection

@section('section-body')
    {{-- Flash Messages --}}
    @include('backend.components.alerts')
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <a href="{{ route('announcement.index') }}" class="btn btn-primary" title="Kembali"><i class="fas fa-home"></i></a>
          </div>

          <div class="card-body">
            
            {!! Form::model($announcement, [
              'route' => $announcement->exists ? ['announcement.update', $announcement->id] : 'announcement.store',
              'method' => $announcement->exists ? 'PUT' : 'POST',
            ]) !!}

              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    {!! Form::label('title', 'Judul') !!}
                    <input 
                      type="text" 
                      name="title" 
                      value="{{ $announcement->exists ? $announcement->title : old('title') }}"
                      class="form-control @error('title') is-invalid @enderror"
                    >

                    @error('title')
                      <div class="invalid-feedback">
                        <span><i class="fas fa-exclamation-circle"></i> {{ $message }}</span>
                      </div>
                    @enderror
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    {!! Form::label('subject', 'Perihal') !!}
                    <input 
                      type="text" 
                      name="subject" 
                      value="{{ $announcement->exists ? $announcement->subject : old('subject') }}"
                      class="form-control @error('subject') is-invalid @enderror"
                    >
                    
                    @error('subject')
                      <div class="invalid-feedback">
                        <span><i class="fas fa-exclamation-circle"></i> {{ $message }}</span>
                      </div>
                    @enderror
                  </div>
                </div>

                <div class="col-md-12">
                  <div class="form-group">
                    {!! Form::label('description', 'Deskripsi') !!}
                    <textarea 
                      name="description" 
                      class="form-control summernote @error('description') is-invalid @enderror"
                    >
                      {{ $announcement->exists ? $announcement->description : old('description') }}
                    </textarea>
                  
                    @error('description')
                      <div class="invalid-feedback">
                        <span><i class="fas fa-exclamation-circle"></i> {{ $message }}</span>
                      </div>
                    @enderror
                  </div>
                </div>

                <div class="col-md-12">
                  <div class="form-group">
                    {!! Form::label('date_time', 'Tanggal & Waktu') !!}
                    <input 
                      type="text" 
                      name="date_time" 
                      class="form-control datetimepicker @error('date_time') is-invalid @enderror"
                      value="{{ $announcement->exists ? $announcement->date_time : old('date_time') }}"
                      autocomplete="off"
                    >

                    @error('description')
                      <div class="invalid-feedback">
                        <span><i class="fas fa-exclamation-circle"></i> {{ $message }}</span>
                      </div>
                    @enderror
                  </div>
                </div>
              </div>

              <button type="submit" class="btn btn-success">Simpan</button>

            {!! Form::close() !!}

          </div>
        </div>
      </div>
    </div>
@endsection

@push('scripts')
    <script src="{{ asset('backend/develop/js/helper.js') }}"></script>
    <script>
      $(function () {
        dateTimePicker('.datetimepicker')
      })
    </script>
@endpush

resources/views/backend/pages/general/announcements/index.blade.php
@extends('backend.layouts.app')

@section('section-header')
    Pengumuman
@endsection

@section('breadcrumbs')
    {{ Breadcrumbs::render('announcement') }}
@endsection

@section('section-body')
    {{-- Flash Messages --}}
    @include('backend.components.alerts')
    <div class="card">
        <div class="card-header">
            <a href="{{ route('announcement.create') }}" class="btn btn-sm btn-primary" title="Buat Pengumuman">
                <i class="fas fa-plus"></i>
            </a>
            <a href="{{ route('announcement.index') }}" class="btn btn-sm btn-success ml-2" id="refresh-data" title="{{ __('Segarkan') }}">
                <i class="fas fa-sync" id="refresh-animation"></i>
            </a>
        </div>

        <div class="card-body">
            <div class="table table-responsive">
                <table class="table-striped" id="datatable" style="width: 100%">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Judul</th>
                            <th>Subjek</th>
                            <th>Dibuat Oleh</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script src="{{ asset('backend/develop/js/dataTablesService.js') }}"></script>
    <script src="{{ asset('backend/develop/js/admin/announcements/index.js') }}"></script>
@endpush

resources/views/backend/pages/general/announcements/show.blade.php
<div class="row">
  <div class="col-md-12">
    {!! $announcement->description !!}
  </div>
</div>