routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/**
 * ----------------------------------------------
 * Admin Routes
 * ----------------------------------------------
 * 
 * Here is where you can register your admin panel routes.
 */
Route::group(['middleware' => ['auth']], function () {
    Route::get('/', 'BackendController@dashboard')->name('admin');
    
    // Profiles
    Route::namespace('Profile')->prefix('profile')->group(function() {
        Route::get('/{id}', 'ProfileController@index')->name('profile.index');
        // Update profile
        Route::put('/{id}/update', 'ProfileController@update')->name('profile.update');
        // Remove Image
        Route::get('/{id}/image/deleted', 'ProfileController@deleteImage')->name('image.delete');
        // Delete Profile
        Route::delete('/{id}/profile/delete', 'ProfileController@delete')->name('profile.delete');
    
        // Change Password
        Route::put('/{id}/password/update', 'PasswordController@update')->name('password.change');
    });
    
    // Master Route
    Route::namespace('Master')->prefix('master')->group(function () {
        Route::get('/user/datatables', 'UserController@userDataTables');
        Route::resource('user', 'UserController');
        Route::get('/role/datatables', 'RoleController@roleDataTables');
        Route::resource('role', 'RoleController');
    });
    
    // General Route
    Route::get('/takmir/datatables', 'TakmirController@takmirDataTables');
    Route::resource('takmir', 'TakmirController');
    Route::get('/announcement/datatables', 'AnnouncementController@announcementsDataTables');
    Route::resource('announcement', 'AnnouncementController');
    Route::get('/kajian/datatables', 'KajianController@kajianDataTables');
    Route::resource('kajian', 'KajianController');
    Route::get('/gallery/datatables', 'GalleryController@galleryDataTables');
    Route::resource('gallery', 'GalleryController');
    Route::get('/contact/datatables', 'ContactController@contactDataTables');
    Route::resource('contact', 'ContactController');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontController@home')->name('home');
Route::get('/announcement', 'AnnouncementController@index')->name('announcement');
Route::get('/announcement/detail/{id}', 'AnnouncementController@show')->name('announc.detail');
Route::get('/donate', 'FrontController@donate')->name('donate');
Route::get('/kajian', 'KajianController@index')->name('kajian');
Route::get('/kajian/detail/{id}', 'KajianController@show')->name('kajian.detail');
Route::post('/contact', 'ContactController@store')->name('contact.send');

Auth::routes();

Route::get('/home', 'HomeController@index');

app/Models/Contact.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    /**
     * Get formatted created at
     */
    public function getFormattedCreatedAt() {
        return Carbon::parse($this->created_at)->diffForHumans();
    }
}

app/Http/Controllers/Admin/ContactController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Interfaces\ContactInterface;

class ContactController extends Controller
{
    protected $contactInterface;

    /**
     * Construct
     */
    public function __construct(ContactInterface $contactInterface) {
        $this->contactInterface = $contactInterface;
    }
    
    /**
     * Redirecting to contact index
     */
    public function index() {
        return view('backend.pages.general.contacts.index');
    }

    /**
     * Detail of contact
     * 
     * @param int $id
     */
    public function show($id) {
        $contact = $this->contactInterface->getContactById($id);

        return view('backend.pages.general.contacts.show', compact('contact'));
    }

    /**
     * Delete contact from the database
     * 
     * @param int $id
     */
    public function destroy($id) {
        return $this->contactInterface->deleteContact($id);
    }

    /**
     * Get contact datatables
     * 
     * @param Request
     */
    public function contactDataTables(Request $request) {
        return $this->contactInterface->requestContacts($request);
    }
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Interfaces\ContactInterface;
use App\Http\Requests\ContactRequest;

class ContactController extends Controller
{
    protected $contactInterface;

    /**
     * Construct
     */
    public function __construct(ContactInterface $contactInterface) {
        $this->contactInterface = $contactInterface;
    }

    /**
     * Store contact into the database
     * 
     * @param ContactRequest $request
     */
    public function store(ContactRequest $request) {
        return $this->contactInterface->storeToDB($request);
    }
}

resources/views/backend/pages/general/contacts/index.blade.php
@extends('backend.layouts.app')

@section('section-header')
    Pesan
@endsection

@section('breadcrumbs')
    {{ Breadcrumbs::render('contact') }}
@endsection

@section('section-body')
    {{-- Flash Messages --}}
    @include('backend.components.alerts')
    <div class="card">
        <div class="card-header">
            <a href="{{ route('contact.index') }}" class="btn btn-sm btn-success ml-2" id="refresh-data" title="{{ __('Segarkan') }}">
                <i class="fas fa-sync" id="refresh-animation"></i>
            </a>
        </div>

        <div class="card-body">
            <div class="table table-responsive">
                <table class="table-striped" id="datatable" style="width: 100%">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Nama</th>
                            <th>Email</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script src="{{ asset('backend/develop/js/dataTablesService.js') }}"></script>
    <script src="{{ asset('backend/develop/js/admin/contacts/index.js') }}"></script>
@endpush

resources/views/backend/pages/general/contacts/show.blade.php
<table class="table table-striped">
  <tr>
    <th>Nama</th>
    <td>:</td>
    <td>
      {{ $contact->name }}
    </td>
  </tr>
  <tr>
    <th>Email</th>
    <td>:</td>
    <td>
      {{ $contact->email }}
    </td>
  </tr>
  <tr>
    <th>Subjek</th>
    <td>:</td>
    <td>
      {{ $contact->subject }}
    </td>
  </tr>
  <tr>
    <th>Pesan</th>
    <td>:</td>
    <td>
      {{ $contact->body }}
    </td>
  </tr>
  <tr>
    <th>Dibuat</th>
    <td>:</td>
    <td>
      {{ $contact->created_at }} - 
      ({{ $contact->getFormattedCreatedAt() }})
    </td>
  </tr>
</table>